### ISSUE TITLE
Not seeing telemetry in Aspire dashboard

### ISSUE THREAD

**Issue by tskimmett** [Doxense/foundationdb-dotnet-client#141]
So far this project looks great and the actual FDB interaction is working perfectly. My only question is about how to get open telemetry working. As far as I can tell, tracing and metrics are enabled on the db client by default, but I'm not seeing anything in the aspire dashboard. I also noticed that individual transactions had null `Log` properties. I'm guessing I've just misconfigured something.

**Comment by KrzysFR** [comment]
Are you talking about spans and metrics?

I am declaring the fdb resources in the AppHost like this, and I can control the tracing options for all processes that will reference this resource.
```csharp
var fdb = builder
	.AddFoundationDb("fdb", apiVersion: 720, root: "/Sandbox/HelloWorld", clusterVersion: "7.3.54", rollForward: FdbVersionPolicy.Exact)
	.WithDefaults(timeout: TimeSpan.FromSeconds(15), retryLimit: 10, tracing: FdbTracingOptions.All)
	.WithLifetime(ContainerLifetime.Persistent)
	;
```

The call to `WithDefaults(...., tracing: FdbTracingOptions.All) changes the default tracing options to All for all over resources that will reference the `fdb` resource. `All` includes more detailed spans and metrics, but with `Default` you should already see some entries. With this, I can see spans in the dashboard:

![image](https://github.com/user-attachments/assets/8f15b386-d652-473b-91c1-c716b3194f15)

![image](https://github.com/user-attachments/assets/c5b8fcf0-34ee-4470-bcf0-701fb4fffd3a)

As well as metrics:
![image](https://github.com/user-attachments/assets/7e8a66e3-72f0-4368-8678-91dccb456026)

For both Metrics and Activities, the source name is `FoundationDB.Client` and you may have to change the log level in you appsettings.json file, depending on the logging library that you are using (Serilog? default .NET implementation?)

I looked in the ServiceDefaults and appsettings.json I am using, and did not see any other particular settings.

**Comment by tskimmett** [comment]
Yeah, spans and metrics. The main difference I see on my end is that I specified api version 730 and I'm using an ARM-based fdb docker image. I'll play around with that. Thanks for the quick response!

**Comment by tskimmett** [comment]
Yeah, the fdb container is running fine and I have a simple console application to do some basic benchmarking of reads/writes.

**Comment by tskimmett** [comment]
Turns out it was just because I wasn't calling `app.StartAsync()` with my console app setup. Thanks for all the info. I'll go ahead and close this issue.
