### ISSUE TITLE
Tag tests that requires a working local FDB install for hosted CI servers

### ISSUE THREAD

**Issue by KrzysFR** [Doxense/foundationdb-dotnet-client#59]
In order to run the unit tests, we need a local install of FDB, which is not always possible on hosted CI servers (Travis, AppVeyor, ...), so unit tests are not run by default.

But there is a whole set of unit tests that do not need to connect to the db (tuples, async linq, ...) which could at least run without fdb_c.dll.

Idea would be to add a NUnit test category "RequiresFDB" that would be blacklisted on CI servers.

**Comment by jvandertil** [comment]
This seems like a 1 line fix, add:
```
[Category("RequiresFDB")]
```

to the FdbTest class

**Comment by KrzysFR** [comment]
Yes probably. If there are some methods in these classes that do not use the db itself, they should probably be put in a different class.
