### ISSUE TITLE
Target API version 510 by default

### ISSUE THREAD

**Issue by KrzysFR** [Doxense/foundationdb-dotnet-client#63]
The current default API version is __300__, which correspond to the v3.x of FoundationDB. The latest version available is now v5.1.5, which add some features compare to the old v3.x (more atomic operation types, and versionstamp).

Since not a lot of people are probably using the .NET binding in production, and since probably most people would jump straight to v5.1, I think that it is reasonable to target API version __510__ by default.

This means that application that do not explicitly request an API version, or call `Fdb.Start()` without arguments, would now default to the latest API v500. It is unknown at this time if there has been changes to the behavior of existing commands between 300 and 510.

_Looking at other binding (java, python, etc...) it appears that some have dropped support for pre-510 versions._

**Comment by ajbeamon** [comment]
Our latest released API version as of 5.1 is 510. We did drop support for older API versions in some bindings because of breaking changes to the APIs, but where possible we've tried to continue supporting for older versions.

**Comment by KrzysFR** [comment]
Since I have the _luxury_ to not have to support older API versions, I can simply target __510__ by default, and add support for all the new APIs. We'll see how to handle API versioning in the next round of updates.

**Comment by KrzysFR** [comment]
This has been changed in 80f4312c to API  version __510__ by default. I'm tracking a few regressions which seem to date back from API 300 so probably pre-existing issues.
